[CHA-1570] Update User.java
sailthru/sailthru-java-client pull request #79
Opened 2023-03-29 11:51 UTC by chin-sail

added sms_marketing_status and sms_transactional_status

2023-03-29 18:46 UTC, azinger-sailthru requested changes
Another bit of feedback I have is with regard to design.  Since this is a client library, could we encapsulate allowable values for the two SMS consent fields?

https://getstarted.sailthru.com/developers/api/user/#POSTParameters outlines that for both `sms_marketing_status` and `sms_transactional_status`, the only allowable values are:
- `"opt-in"`
- `"opt-out"`

I'd prefer to keep that internal to the client library and make our interface such as these getter and setter methods for these attributes act in a way that prevents bad inputs by the library user code (going into the setter) and bad outputs from ever being given to the library user code (from the getter).

This limiting of values can be done with an `enum` type.

2023-03-29 18:46 UTC, azinger-sailthru commented on src/main/com/sailthru/client/params/User.java
> +    public User setSms_marketing_status(String sms_marketing_status) {
Are we able to follow standard Java naming conventions for methods being camel-case?  https://www.javatpoint.com/java-naming-conventions
```suggestion
    public User setSmsMarketingStatus(String smsMarketingStatus) {
```

2023-03-29 18:46 UTC, azinger-sailthru commented on src/main/com/sailthru/client/params/User.java
> +        this.sms_marketing_status = sms_marketing_status;
```suggestion
        this.smsMarketingStatus = smsMarketingStatus;
```

2023-03-29 18:46 UTC, azinger-sailthru commented on src/main/com/sailthru/client/params/User.java
> +    public User setSms_transactional_status(String sms_transactional_status) {
```suggestion
    public User setSmsTransactionalStatus(String smsTransactionalStatus) {
```

2023-03-29 18:46 UTC, azinger-sailthru commented on src/main/com/sailthru/client/params/User.java
> +        this.sms_transactional_status = sms_transactional_status;
```suggestion
        this.smsTransactionalStatus = smsTransactionalStatus;
```

2023-03-29 18:46 UTC, azinger-sailthru commented on src/main/com/sailthru/client/params/User.java
> +    protected String sms_marketing_status;
```suggestion
    protected String smsMarketingStatus;
```

2023-03-29 18:46 UTC, azinger-sailthru commented on src/main/com/sailthru/client/params/User.java
> +    protected String sms_transactional_status;
```suggestion
    protected String smsTransactionalStatus;
```

2023-03-30 11:52 UTC, chin-sail commented on src/main/com/sailthru/client/params/User.java
> +    protected String sms_marketing_status;
field name should follow the json format as "sms_marketing_status" otherwise it won't be converted the proper field name

2023-03-30 11:53 UTC, chin-sail commented on src/main/com/sailthru/client/params/User.java
> +    protected String sms_transactional_status;
field name should follow the json format as "sms_transactional_status" otherwise it won't be converted the proper field name

2023-03-30 11:54 UTC, chin-sail commented on src/main/com/sailthru/client/params/User.java
> +    public User setSms_marketing_status(String sms_marketing_status) {
changed the method name to adhere to the java naming conventions

2023-03-30 11:56 UTC, chin-sail commented on src/main/com/sailthru/client/params/User.java
> +    public User setSms_transactional_status(String sms_transactional_status) {
changed the method parameter name

2023-03-30 16:25 UTC, azinger-sailthru requested changes

2023-03-30 16:25 UTC, azinger-sailthru commented on src/main/com/sailthru/client/params/User.java
> +    protected String sms_marketing_status;
I suspect you're right that the way this library is set up right now, deviating from `sms_marketing_status` to camel case will break.  But I think there's a way to make it work with an annotation.

### Analysis
Here's a little detour into what I think is going on -- let me know if any of this doesn't sound right.  Here's the method that is used to make all HTTP calls to Sailthru API: https://github.com/sailthru/sailthru-java-client/blob/3d61b585c6dc8cfd465e2d0ef0b7a0e7fba950b1/src/main/com/sailthru/client/AbstractSailthruClient.java#L147-L163  It relies on Google's GSON library for Java-JSON serialization and deserialization.  There is a central place, where our GSON serializer is initialized: https://github.com/sailthru/sailthru-java-client/blob/3d61b585c6dc8cfd465e2d0ef0b7a0e7fba950b1/src/main/com/sailthru/client/SailthruUtil.java#L52-L56  As you can see, it stays pretty close to defaults.  GSON allows some different naming translations to be used between Java and JSON using what it calls naming policies.

Here's a tutorial with an overview of GSON naming policies: https://futurestud.io/tutorials/gson-builder-basics-naming-policies  Note that the default naming policy is `IDENTITY`, which makes no changes to the field names at all.  Here's the full set of API for `GsonBuilder` that shows what _can_ be configured: https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/GsonBuilder.html

### What to do
I think it should be possible for us to just override serialization name of these SMS consent properties using `@SerializedName` annotation here without changing any global GSON settings.  That would let us use standard Java naming conventions for the new fields and not introduce too much risk elsewhere.  I'd like to suggest that we try this approach now.

A more elaborate change would be to try to apply GSON naming policy `LOWER_CASE_WITH_UNDERSCORES`, but we'd have to be really careful to make sure we don't break anything, so we'd have to look at the level of unit test coverage and see how much additional unit test code would be needed.  I think this can be something we propose to the library maintainers for later.

2023-03-30 16:25 UTC, azinger-sailthru commented on src/main/com/sailthru/client/params/User.java
> +        this.sms_marketing_status = optOutType.optOutTypeStr;
I think we can let this field be itself of type `OptOutType` and make sure GSON serialize it.  We may need to register a custom serializer to handle this particular enum: https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.0/com/google/gson/GsonBuilder.html#registerTypeAdapter-java.lang.reflect.Type-java.lang.Object-

This is something we should definitely add unit test coverage for.

2023-03-31 03:24 UTC, chin-sail commented on src/main/com/sailthru/client/params/User.java
> +    protected String sms_marketing_status;
I've followed the approach and used the `@SerializedName` annotation to serialize the fields and used the adaptor to read the valued through OptoutType enum.

2023-03-31 03:26 UTC, chin-sail commented on src/main/com/sailthru/client/params/User.java
> +        this.sms_marketing_status = optOutType.optOutTypeStr;
I've adopted this approach and implemented a custom serializer.

2023-04-03 02:22 UTC, chin-sail commented on src/main/com/sailthru/client/params/User.java
> +    protected String sms_transactional_status;
used the java naming conventions for the field name

2023-04-03 13:28 UTC, azinger-sailthru reviewed
Looking really good.  Just wondering about that one extra file now.

2023-04-03 13:28 UTC, azinger-sailthru commented on pom.xml.versionsBackup
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.
Is this new file meant to be checked in?

2023-04-04 11:57 UTC, chin-sail commented on pom.xml.versionsBackup
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.
This was deleted as it was accidently checked in.

2023-04-10 14:12 UTC, azinger-sailthru approved these changes

2023-04-10 20:24 UTC, scshull119 approved these changes
+1, with one non-blocking comment

2023-04-10 20:24 UTC, scshull119 commented on pom.xml
> +        <tag>sailthru-java-client-2.3.1</tag>
Is there a reason why we tag this `2.3.1` instead of `2.3.2`?

2023-04-17 00:20 UTC, merged